### ISSUE TITLE
Spicetified Spotify not sharing activity properly

### ISSUE THREAD

**Issue by Akasiek** [spicetify/spicetify-cli#1942] opened 2022-09-18 20:35 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.94.870.gf994cb0b
- Spicetify version: 2.13.1
```

### 📝 Description

After updating Spicetify from 2.12 to 2.13.1 found this bug when checking my Last.fm activity. There was no scrobbling from Spicetify Spotify (there was from mobile Spotify and other sources).
Also mobile Spotify was not seeing the Desktop Spotify and vice versa. So I cannot control my Spotify from my phone.

### 📸 Screenshots

No mobile device (or any other activity):
![image](https://user-images.githubusercontent.com/37307597/190927212-b57c1a23-3750-40a9-920d-aa54f1be4d6c.png)

**Comment by kyrie25** [comment] 2022-09-18 22:48
Duplicate of #1938

**Closed by kyrie25** 2022-09-18 22:48 UTC
Labels: 🐛 bug
