### ISSUE TITLE
[Lyric Plus] Traditional Chinese to Simplified Chinese doesn't work properly

### ISSUE THREAD

**Issue by Aurora-Simba** [spicetify/spicetify-cli#2778] opened 2024-01-22 10:02 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: the lastest
- Spicetify version: the lastest
```

### 📝 Description

When I encounter Traditional Chinese lyrics, a Translating prompt box appears, but it does not work. The Traditional Chinese detection is 5%, the convert is also on

**Comment by rxri** [comment] 2024-01-22 10:14
You can override the detection then

**Comment by Aurora-Simba** [comment] 2024-01-22 12:36
> You can override the detection then

I have tried 10% 40% 100% 0%

**Comment by Aurora-Simba** [comment] 2024-01-22 12:41
> You can override the detection then

It doesn't work.Translating is also appear，But it stays Traditional chinese

**Comment by Aurora-Simba** [comment] 2024-01-22 13:39
> You can override the detection then

And I tried Japanese，it works properly.

**Comment by Aurora-Simba** [comment] 2024-01-22 14:34
> You can override the detection then

To be precise, only Japanese has taken effect.

**Comment by rxri** [comment] 2024-01-22 15:32
link to example song?

**Comment by Aurora-Simba** [comment] 2024-01-23 01:07
> link to example song?

https://open.spotify.com/track/0hAmNalTo8tOdDxFekAFSQ?si=55e688b5fa504e10

**Comment by Aurora-Simba** [comment] 2024-01-24 09:48
> link to example song?

Excuse me, Could you give me some feedback?
@rxri

**Comment by Aurora-Simba** [comment] 2024-01-27 02:03
> link to example song?

I sincerely hope to get a reply.
@rxri

**Comment by rxri** [comment] 2024-02-01 01:23
Didn't test it. Opening the issue so I don't forget

**Comment by surya27895** [comment] 2024-02-02 10:17
I don't know if this related or not (if not related i will open an another issues latter) but Translation Hangul to Romaja in Lyrics Plus also affected and not works
![image](https://github.com/spicetify/spicetify-cli/assets/22859567/72fc1d42-13ab-4e3c-812d-eb55642a534b)

**Comment by Aurora-Simba** [comment] 2024-02-02 15:48
> I don't know if this related or not (if not related i will open an another issues latter) but Translation Hangul to Romaja in Lyrics Plus also affected and not works
> ![image](https://github.com/spicetify/spicetify-cli/assets/22859567/72fc1d42-13ab-4e3c-812d-eb55642a534b)
> 

In my opinion, it is relevant, the principle is to use the thesaurus, only the Japanese can work properly.

**Comment by rxri** [comment] 2024-02-02 16:17
> I don't know if this related or not (if not related i will open an another issues latter) but Translation Hangul to Romaja in Lyrics Plus also affected and not works ![image](https://private-user-images.githubusercontent.com/22859567/301810334-72fc1d42-13ab-4e3c-812d-eb55642a534b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTA3NDgsIm5iZiI6MTcwNjg5MDQ0OCwicGF0aCI6Ii8yMjg1OTU2Ny8zMDE4MTAzMzQtNzJmYzFkNDItMTNhYi00ZTNjLTgxMmQtZWI1NTY0MmE1MzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE2MTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYTczYjk4YzFhNzkyNWQyZmQwYWMwODI1MzBiYTg4YjRjYzRiM2Y1NDJhNjU1OWI0ZjZjOTMwNzg1Mjk5NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oOvLrVhBFYp8Pp5eLf94U0P_SZnXmNcgBT0WWP8fHRQ)

![image](https://github.com/spicetify/spicetify-cli/assets/9348108/90eb1c13-bb60-4739-b47a-94f97ae64b3c)
what's the problem here? It works just fine on my end

**Comment by rxri** [comment] 2024-02-02 16:20
> > link to example song?
> 
> [open.spotify.com/track/0hAmNalTo8tOdDxFekAFSQ?si=55e688b5fa504e10](https://open.spotify.com/track/0hAmNalTo8tOdDxFekAFSQ?si=55e688b5fa504e10)
> 
> @rxri

![image](https://github.com/spicetify/spicetify-cli/assets/9348108/f4d04d51-48e3-48b9-83ac-96f88ff63aa0)
It works just fine as well. Please make sure you do not have jsdelivr.net blocked because that's from where lyrics-plus fetches translators/analyzers etc.
Closing since I cannot reproduce the problem

**Closed by rxri** 2024-02-02 16:20 UTC
Labels: 🐛 bug, 🔴 custom app

**Comment by surya27895** [comment] 2024-02-02 16:25
> > I don't know if this related or not (if not related i will open an another issues latter) but Translation Hangul to Romaja in Lyrics Plus also affected and not works ![image](https://private-user-images.githubusercontent.com/22859567/301810334-72fc1d42-13ab-4e3c-812d-eb55642a534b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTA3NDgsIm5iZiI6MTcwNjg5MDQ0OCwicGF0aCI6Ii8yMjg1OTU2Ny8zMDE4MTAzMzQtNzJmYzFkNDItMTNhYi00ZTNjLTgxMmQtZWI1NTY0MmE1MzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE2MTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYTczYjk4YzFhNzkyNWQyZmQwYWMwODI1MzBiYTg4YjRjYzRiM2Y1NDJhNjU1OWI0ZjZjOTMwNzg1Mjk5NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oOvLrVhBFYp8Pp5eLf94U0P_SZnXmNcgBT0WWP8fHRQ)
> 
> ![image](https://private-user-images.githubusercontent.com/9348108/301904658-ccb05bee-ba7b-4a87-8d41-e637dbfee60a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTEzMDIsIm5iZiI6MTcwNjg5MTAwMiwicGF0aCI6Ii85MzQ4MTA4LzMwMTkwNDY1OC1jY2IwNWJlZS1iYTdiLTRhODctOGQ0MS1lNjM3ZGJmZWU2MGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTYyMzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFjMzU3YTc2MWE3NTU1NjE2NDM2NmM5ZjQzNjMxMGQ3MDVmZjc0YjAwYzc0YmMxNmY5NjM4MWVlMWZhMTViMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IZpCiX254fjU8SJzMmfvy-nAmS0PrO3tYe2QGYS18Oc) It works just fine on my end. Are you sure you don't have jsdelivr CDN blocked perhaps?

already trying use vpn, but still same, looking at dev console and not see any error, I don't know what's wrong with mine 😅

**Comment by rxri** [comment] 2024-02-02 16:26
If you join our discord server, I might be able to help you with solving this issue
https://discord.gg/VnevqPp2Rr

**Comment by surya27895** [comment] 2024-02-02 16:29
> If you join our discord server, I might be able to help you with solving this issue https://discord.gg/VnevqPp2Rr

i will try completely reinstaling spotify and spicetify first and reach you on discord if it still same, thanks for help!

**Comment by surya27895** [comment] 2024-02-02 17:41
I got it works after downgrading to v2.29.1, tested on spotify 1.2.30.1135.g02fef27a and 1.2.29.605.g66a43ceb, the translation still works, then test again upgrading to 2.30.0 then it broken again. I think i will keep using v2.29.1 until next release.

**Comment by rxri** [comment] 2024-02-02 17:53
Okay i think i know why it works for me. I use latest changes from repo and I have included this commit: https://github.com/spicetify/spicetify-cli/commit/e6a51face4b1cf112b99d3d57d6c8f07103b60c0. It should fix it and it will land in next release of spicetify. I apologize for not checking it further

**Comment by Aurora-Simba** [comment] 2024-02-03 06:35
> I got it works after downgrading to spicetify v2.29.1, tested on spotify 1.2.30.1135.g02fef27a and 1.2.29.605.g66a43ceb, the translation still works, then test again upgrading to 2.30.0 then it broken again. I think i will keep using v2.29.1 until next release.
> 
> 
> 

thanks

**Comment by Aurora-Simba** [comment] 2024-02-03 06:35
> Okay i think i know why it works for me. I use latest changes from repo and I have this commit included already: https://github.com/spicetify/spicetify-cli/commit/e6a51face4b1cf112b99d3d57d6c8f07103b60c0. This should fix it and it will land in next release of spicetify. I apologize for not checking it further

thanks

**Comment by Aurora-Simba** [comment] 2024-02-05 07:31
> Okay i think i know why it works for me. I use latest changes from repo and I have this commit included already: https://github.com/spicetify/spicetify-cli/commit/e6a51face4b1cf112b99d3d57d6c8f07103b60c0. This should fix it and it will land in next release of spicetify. I apologize for not checking it further

In the 2.31.0，this issue still exists for me.
