### ISSUE TITLE
CosmosAsync "request failed with error code -1 (Resolver not found!)"

### ISSUE THREAD

**Issue by brimell** [spicetify/spicetify-cli#2842] opened 2024-02-16 00:58 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c
- Spicetify version: 1.0.17
- platform: "Win32_x86_64"
```

### 📝 Description

Essentially, not allowing me to add a track to a playlist at all. I've checked that the track URI and playlist ID both work on the spotify developer platform (here: https://developer.spotify.com/documentation/web-api/reference/add-tracks-to-playlist).

```js
Error: POST request to https://api.spotify.com/v1/playlists/4Xy4g6S1EY3GiOcIjdkFj7/tracks?uris=spotify%3Atrack%3Gq3uFAdJltar4ddwboPby request failed with error code -1 (Resolver not found!)
```

when:
```js
export async function addTrackToPlaylist(playlistUri: string, trackUri: string) {
    try {
        const playlistId = playlistUriToPlaylistId(playlistUri);
        console.log(`@${playlistId}@`, `@${trackUri}@`);

        // Make POST request to add track to playlist
        await Spicetify.CosmosAsync.post(`https://api.spotify.com/v1/playlists/${playlistId}/tracks`, {
            uris: [trackUri],
        });

        console.log("Added track to playlist");
    } catch (error) {
        console.error("Error adding track to playlist:", error);
    }
}
```

**Comment by brimell** [comment] 2024-02-16 01:04
I have a feeling I'm being rate limited so I'll check in tomorrow and see what's up...

**Comment by ohitstom** [comment] 2024-02-16 01:08
use platform methods

**Comment by brimell** [comment] 2024-02-16 02:06
Are there platform methods for adding tracks to playlists? I can't find that in the docs

**Comment by brimell** [comment] 2024-02-16 02:15
Thanks so much for the quick reply - trying this rn

**Comment by brimell** [comment] 2024-02-16 02:25
Ok cool. Thanks so much for the help this works and actually looks quite nice as well!

**Comment by brimell** [comment] 2024-02-16 02:29
- would be nice to have this added to the docs though (and maybe you could direct me to where I could find types for the platform methods?)

**Comment by ohitstom** [comment] 2024-02-16 02:33
> * would be nice to have this added to the docs though (and maybe you could direct me to where I could find types for the platform methods?)

platform methods are managed by spotify, we just allow developers to access them, and as such making docs would be painstakingly difficult as every spotify update changes many of them without our knowledge.

Your best bet for finding them is just looking through the Spicetify.Platform object yourself and looking at how the functions themselves work in xpui to figure out the props to pass

**Comment by brimell** [comment] 2024-02-16 02:36
Ok yeah good idea. I wouldn't mind adding a few things to the platform section on the docs if you don't mind.

**Comment by ohitstom** [comment] 2024-02-16 02:37
> Ok yeah good idea. I wouldn't mind adding a few things to the platform section on the docs if you don't mind.

i am not a maintainer but i dont think they would want that in the docs as again its not something we can control consistently, @rxri would need to talk to you about this

**Comment by rxri** [comment] 2024-02-16 05:03
Platform API will be documented in types and everything in v3 so that’s something we already do and have on eye. Also duplicate of https://github.com/spicetify/spicetify-cli/issues/2837

**Closed by rxri** 2024-02-16 05:03 UTC
Labels: 🐛 bug
