### ISSUE TITLE
Enabling Experimental Features Doesn't Do Anything

### ISSUE THREAD

**Issue by Mcfly2340** [spicetify/spicetify-cli#1558] opened 2022-03-28 08:29 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
OS: Windows v10.0.22581
Spotify: v1.1.81.604
Spicetify: v2.9.4
```

### 📝 Description

writing `spicetify config experimental_features 1`
and next `spicetify apply` doesn't enable the experimental features nor the experimental window in the context menu

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/71077562/160357933-344275e1-43af-4414-a83a-d06de3ae128d.png)

**Comment by afonsojramos** [comment] 2022-03-28 09:18
Duplicate of #1485.

**Closed by afonsojramos** 2022-03-28 09:18 UTC
Labels: 🐛 bug

**Comment by Mcfly2340** [comment] 2022-03-28 09:21
> Duplicate of #1485.

i made the issue because it seemed that #1485 doesn't have any news so i thought i can shed some light on this again

**Comment by afonsojramos** [comment] 2022-03-28 09:22
I pinned that issue now since it is being a recurrent one.
