### ISSUE TITLE
High CPU usage when lyrics-plus is being used

### ISSUE THREAD

**Issue by ameliorability** [spicetify/spicetify-cli#2878] opened 2024-03-03 22:34 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c (Flatpak) (Fedora 39)
- Spicetify version: v2.33.2
Extensions: trashbin.js
Custom Apps: marketplace, lyrics-plus
```

### 📝 Description

When using lyrics-plus, CPU usage rises rapidly, from about <5% to 15-20%. Occurs whenever lyrics-plus is being used, and with other extensions that integrate lyrics-plus (e.g. Full Screen by daksh2k). Did not occur in previous Spicetify version.

Steps: play a song and open lyrics-plus

Expected: When using lyrics-plus, CPU is calm and happy as always, <5% usage by Spotify

Observed: When using lyrics-plus, CPU gets wildly loud and hot, 15-20% usage by Spotify

### 📸 Screenshots

With lyrics-plus DISABLED: 
![image](https://github.com/spicetify/spicetify-cli/assets/141889580/0edc1570-6ada-4cbf-b526-d057cb7acfe6)

With lyrics-plus ENABLED but not being used:
![image](https://github.com/spicetify/spicetify-cli/assets/141889580/726e7350-5271-4fbe-8326-2710e50cc741)

With lyrics-plus ENABLED and being used: 
![image](https://github.com/spicetify/spicetify-cli/assets/141889580/314ef314-5786-40d8-b2a4-4607841b0408)

**Comment by rxri** [comment] 2024-03-03 22:35
Duplicate of #2877. Let's keep all the discussion in one place

**Closed by rxri** 2024-03-03 22:35 UTC
Labels: 🐛 bug, 🔴 custom app, 🔵 extension
