### ISSUE TITLE
No home screen

### ISSUE THREAD

**Issue by fs2137** [spicetify/spicetify-cli#1475] opened 2022-02-15 19:54 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

Hi after installing spicetify i cant load to home screen. Can you help me solve this?

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/99762604/154138477-cfeb371a-5d0d-4612-9a62-f56ac45b3a57.png)

**Comment by afonsojramos** [comment] 2022-02-16 01:24
Please specify Spicetify and Spotify versions.

**Comment by Inovvia** [comment] 2022-02-18 06:31
Not OP but

Spotify for Windows
1.1.79.763.gc2965cdf

Spiceitfy 2.8.3

![image](https://user-images.githubusercontent.com/70137651/154630040-8242ffcf-a267-45b1-a7ef-cbbc6119bb09.png)

**Comment by tawniey** [comment] 2022-03-04 04:24
Same issue here suddenly. Spotify  1.1.80.699 (for Windows)
Spicetify v 2.9.2

First occurred after an update reload. Followed instructions on FAQ and uninstalled/reinstalled spotify. reapplied spicetify, no change. Cleared spicetify backup and repeated initial steps. Same result again. Just a black screen with the "..." in the top left and the control buttons on the top right. Running on Windows 11 (web install, not MS store install)

**Comment by noiseexplosion** [comment] 2022-03-04 06:28
> Not OP but
> 
> Spotify for Windows 1.1.79.763.gc2965cdf
> 
> Spiceitfy 2.8.3
> 
> ![image](https://user-images.githubusercontent.com/70137651/154630040-8242ffcf-a267-45b1-a7ef-cbbc6119bb09.png)

same problem as well! new user and tried all the troubleshooting methods. on windows 10, installed through the website (not store) and fully updated

**Comment by SakethKanchi** [comment] 2022-03-04 18:13
Same issue
![image](https://user-images.githubusercontent.com/70198692/156818240-8fd1adc9-b3c3-49d3-a812-9570364b25b7.png)

Spotify Version: V1.1.80.699
Spicetify Version: V2.9.2

**Comment by bramdsgn** [comment] 2022-03-04 18:33
Same here / MacOS

Spotify for Windows 1.1.80.699.gc3dac750
Spicetify V2.9.2

**Comment by iDCoded** [comment] 2022-03-05 12:50
**Spicetify** version: `2.9.2`
**Spotify** version: `Spotify for Windows 1.1.80.699.gc3dac750`

--- 

Theme : `Dribbblish`
Color scheme : `Nord Dark`
Extensions : `popupLyrics.js, fullAppDisplay.js, webnowplaying.js, dribbblish.js`

--- 

I was facing the same issue.
Whenever I would run `spicetify apply`, Spotify wouldn't load at all and I had to run `spicetify restore` to restore Spotify back to default.

➡️ **FIX**: Open Spotify, go to **Help** and click on **About Spotify**. If a newer version is available i.e **1.1.80** there will be an option to update Spotify. Click on it to update and then restart Spotify. After this, re-run `spicetify apply` and now it should work as intended. 

I cannot 100% assure this, but since it worked for me, I have shared it here. 
Hope it helps :)

**Comment by SakethKanchi** [comment] 2022-03-05 18:28
I fixed this by going back to 
Spotify for Windows 1.1.77.643.g3c4c6fc6
and Spicetify V2.9.1.

**Comment by iDCoded** [comment] 2022-03-05 18:46
> I fixed this by going back to Spotify for Windows 1.1.77.643.g3c4c6fc6 and Spicetify V2.9.1.

It was quite opposite in my case. 
I had to update **Spotify**.

**Comment by afonsojramos** [comment] 2022-03-06 23:42
Spicetify only targets the latest release of Spotify, if you are not using the latest one, please update it. Will close this issue as it is related to mismatched versions.

**Closed by afonsojramos** 2022-03-06 23:42 UTC
Labels: 🐛 bug
