### ISSUE TITLE
Blank screen after new update

### ISSUE THREAD

**Issue by alucardontop** [spicetify/spicetify-cli#1946] opened 2022-09-21 18:00 UTC
``### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon)
1.1.94.870.gf994cb0b
- Spicetify version: v2.13.1
M1 Pro 16 inch (2021)
Version 12.6 (latest)
Memory: 32GB LPDDR5
```

### 📝 Description

After opening Spotify, it was not launching properly. I applied the backup to see the horrific new update and downloaded the latest spicetify version as I was using v2.13.0, but that didn't work either. It's not a problem with my theme, custom apps, or extensions as just the default results in the same thing. 

### 📸 Screenshots

before applying
![new update](https://user-images.githubusercontent.com/89560393/191576482-a9ca3971-5b88-4704-8791-9cad5b306437.jpg)
after applying (black color and not grey due to theme)
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/89560393/191576669-390ac16d-4aea-45b5-94e3-b39e227cb220.png">

`[Setting]
replace_colors          = 1
overwrite_assets        = 0
spotify_launch_flags    = 
check_spicetify_upgrade = 0
spotify_path            = /Applications/Spotify.app/Contents/Resources
prefs_path              = /Users/veer/Library/Application Support/Spotify/prefs
current_theme           = Sleek
color_scheme            = UltraBlack
inject_css              = 1

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions            = shuffle+.js|fullAlbumDate.js|hidePodcasts.js|skipStats.js|volumePercentage.js|showQueueDuration.js|seekSong.js
custom_apps           = lyrics-plus
sidebar_config        = 1
home_config           = 1
experimental_features = 0

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.94.870.gf994cb0b
with    = 2.13.1

`

**Comment by iamririxi** [comment] 2022-09-21 18:13
Duplicate of #1939

**Closed by iamririxi** 2022-09-21 18:13 UTC
Labels: 🐛 bug, 🔴 custom app, 🔵 extension
