### ISSUE TITLE
spicetify won't update to the latest client version

### ISSUE THREAD

**Issue by criss2882** [spicetify/spicetify-cli#1688] opened 2022-05-19 18:01 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest idk wich on is it
- Spicetify version: v2.9.8
```

### 📝 Description

spicetify just won't apply after the latest spotify update

### 📸 Screenshots

[](url)
![Screenshot 2022-05-19 210108](https://user-images.githubusercontent.com/104204409/169367860-c13c8bfb-e37c-44bc-982b-28dd2352f4bc.png)

**Comment by afonsojramos** [comment] 2022-05-19 18:10
Duplicate of #1660

**Closed by afonsojramos** 2022-05-19 18:10 UTC
Labels: 🐛 bug
