### ISSUE TITLE
Requesting to mute all audio ads and banner ads

### ISSUE THREAD

**Issue by gihanadnivak** [spicetify/spicetify-cli#1853] opened 2022-08-03 06:25 UTC
### 📝 Provide a description of the new feature

I want to mute spotify automatically when ad is playing .

**Comment by kyrie25** [comment] 2022-08-03 06:33
Not a bug nor enhancement request for the CLI.  Closing issue.

**Comment by kyrie25** [comment] 2022-08-03 06:33
There are already extensions and other projects that does the trick. We won't be implementing this into the CLI.

**Closed by kyrie25** 2022-08-03 06:33 UTC
Labels: ❌ invalid

**Comment by gihanadnivak** [comment] 2022-08-03 07:15
> There are already extensions and other projects that does the trick. We won't be implementing this into the CLI.

what is the extension ?

**Comment by kyrie25** [comment] 2022-08-03 07:50
That you will have to look around yourself. I am not obliged to provide it in any way.
