### ISSUE TITLE
Can't install Spicetify

### ISSUE THREAD

**Issue by wei44th** [spicetify/spicetify-cli#2471] opened 2023-07-14 00:14 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.15.828
- Spicetify version: -
```

### 📝 Description

Reinstalled my Windows to clear 11 and I can't install Spicetify. Screenshot is pinned below.
I'm not sure if my problem is about my Windows/PowerShell or about Spicetify so I just hope that somebody had this issue

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/56637070/476d09e1-0fc7-460c-919c-70fcd152eac9)

**Comment by kyrie25** [comment] 2023-07-14 00:19
Duplicate of #2469

**Closed by kyrie25** 2023-07-14 00:19 UTC
Labels: 🐛 bug

**Comment by NocetiFederico** [comment] 2023-07-14 19:53
hello, could you solve it? I have the same problem
