### ISSUE TITLE
[Lyrics Plus] There is no way for the lyrics to switch automatically according to the song

### ISSUE THREAD

**Issue by WilliamWangshao** [spicetify/spicetify-cli#2334] opened 2023-05-08 10:26 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: macOS (Intel) 版 1.2.10.760.g52970952
- Spicetify version: v2.18.0
```

### 📝 Description

There is no way for the lyrics to switch automatically according to the song. As in the screenshot below, I have switched to an Chinese song, but the lyrics are still stuck in the first English song played.

### 📸 Screenshots

![截屏2023-05-07 20 01 37](https://user-images.githubusercontent.com/33147340/236796642-ac8d47c5-abda-4c4b-849b-646fd92174a7.png)

**Comment by kyrie25** [comment] 2023-05-08 10:28
Duplicate of #2318

**Closed by kyrie25** 2023-05-08 10:28 UTC
Labels: 🐛 bug, 🔴 custom app

**Comment by WilliamWangshao** [comment] 2023-05-08 10:47
it works！thank you

Nam Anh ***@***.***> 于2023年5月8日周一 18:29写道：
