### ISSUE TITLE
Spotify blank screen after Spicetify installation

### ISSUE THREAD

**Issue by FATiPPO** [spicetify/spicetify-cli#1577] opened 2022-04-08 09:34 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows - 1.1.80.699.gc3dac750
- Spicetify version: Latest
```

### 📝 Description

Spotify always returns with a blank screen after installation of Spicetify, would work normally after uninstalling Spicetify. 
Tried all versions from (73.517) but got the same results. 

Webnowplaying for Rainmeter is not working as well, not sure its relevant but wanted to point out. 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/103251211/162408675-ef65c106-f6a5-4657-bfe9-c47425b8c098.png)

**Comment by sharkiller** [comment] 2022-04-10 08:16
1.1.83 same problem here

**Comment by CruxH** [comment] 2022-04-12 10:30
Working well with 1.1.81.604.gccacfc8c.

**Comment by JamTarty** [comment] 2022-04-12 19:49
I'm having the same issue on 1.1.81.604

**Comment by prateekamana** [comment] 2022-04-13 10:33
I am having the issue with version 1.1.72.439.gc253025e because that's the version available in debian ppa's, but looks like upgrading it won't fix it?

**Comment by ririxidev** [comment] 2022-04-14 08:36
> I am having the issue with version 1.1.72.439.gc253025e because that's the version available in debian ppa's, but looks like upgrading it won't fix it?

1.1.72 isn't supported by spicetify at all. Please use official spotify's repositories to download latest version.

Regarding this issue, please give us more logs.

**Comment by FATiPPO** [comment] 2022-04-14 08:46
> > I am having the issue with version 1.1.72.439.gc253025e because that's the version available in debian ppa's, but looks like upgrading it won't fix it?
> 
> 1.1.72 isn't supported by spicetify at all. Please use official spotify's repositories to download latest version.
> 
> Regarding this issue, please give us more logs.

how can I provide more log for troubleshooting?

**Comment by ririxidev** [comment] 2022-04-14 08:49
Devtools. Please check this comment to learn how to enable them after latest update https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1060122063

**Comment by FATiPPO** [comment] 2022-04-14 09:07
> Devtools. Please check this comment to learn how to enable them after latest update [#1518 (comment)](https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1060122063)

okay all working for me, is there anything specific I should be including as a log? 
I am seeing something like this with my Spotify window. 

![image](https://user-images.githubusercontent.com/103251211/163352600-043dafa2-8ce8-4879-85fb-9cdf8a232789.png)

**Comment by ririxidev** [comment] 2022-04-14 09:17
> > Devtools. Please check this comment to learn how to enable them after latest update [#1518 (comment)](https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1060122063)
> 
> okay all working for me, is there anything specific I should be including as a log? I am seeing something like this with my Spotify window.
> 
> ![image](https://user-images.githubusercontent.com/103251211/163352600-043dafa2-8ce8-4879-85fb-9cdf8a232789.png)

Check console tab for errors.

**Comment by prateekamana** [comment] 2022-04-14 09:20
@ririxidev 
I would love to give more logs but I can't upgrade spotify from the official repos https://www.spotify.com/us/download/linux/ from here
Should I install spotify with snap then? Or are there other repos for debian that provide latest versions, I can't find those...

**Comment by ririxidev** [comment] 2022-04-14 09:25
> @ririxidev
I would love to give more logs but I can't upgrade spotify from the official repos [spotify.com/us/download/linux](https://www.spotify.com/us/download/linux/) from here
Should I install spotify with snap then? Or are there other repos for debian that provide latest versions, I can't find those...

```bash
curl -sS https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg | sudo apt-key add - 
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
```
It should have the at least version 1.80 in repo.
![image](https://user-images.githubusercontent.com/9348108/163355669-66fa240a-9ee3-4f68-ae26-69467391da0f.png)
If not, get deb from [here](http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.80.699.gc3dac750_amd64.deb)

**Comment by prateekamana** [comment] 2022-04-14 09:36
Haha just upgrading it worked apparently, thanks a tonne.

**Comment by FATiPPO** [comment] 2022-04-14 09:46
> > > Devtools. Please check this comment to learn how to enable them after latest update [#1518 (comment)](https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1060122063)
> > 
> > 
> > okay all working for me, is there anything specific I should be including as a log? I am seeing something like this with my Spotify window.
> > ![image](https://user-images.githubusercontent.com/103251211/163352600-043dafa2-8ce8-4879-85fb-9cdf8a232789.png)
> 
> Check console tab for errors.

got this when I skip to the next song

![image](https://user-images.githubusercontent.com/103251211/163359663-4bbecaf2-3eea-4ad1-a1c0-c986d20c8c08.png)

**Comment by Daksh777** [comment] 2022-04-14 14:06
Same problem, Spotify for Windows - 1.1.83.956.gbe7ea9a7

**Comment by afonsojramos** [comment] 2022-04-14 14:33
Here we go again...

**Comment by Daksh777** [comment] 2022-04-14 14:50
@afonsojramos Should I create another issue for the new version, since this issue is made for an older version of the app?

**Comment by afonsojramos** [comment] 2022-04-14 15:10
I guess we can stay with this one. Still applies in a way. The first comment is actually already with the new version either way.

Tip: If you do not want to constantly deal with this, please simply use [spicetify-easyinstall](https://github.com/ohitstom/spicetify-easyinstall) as it fixes the releases of both Spicetify and Spotify.

**Comment by FATiPPO** [comment] 2022-04-14 15:46
> I guess we can stay with this one. Still applies in a way. The first comment is actually already with the new version either way.
> 
> Tip: If you do not want to constantly deal with this, please simply use [spicetify-easyinstall](https://github.com/ohitstom/spicetify-easyinstall) as it fixes the releases of both Spicetify and Spotify.

felt kinda stupid I spent so much time around GitHub and didn't realize this. 

Just reinstalled both Spotify and spicetify, can confirm everything is working now. 
Webnowplaying and theme are both working perfectly as well. 

Thanks so much!

**Comment by Daksh777** [comment] 2022-04-16 04:33
@afonsojramos could you perhaps reopen the issue? Since spicetify-easyinstall is a workaround and not a solution so this issue should remain open

**Comment by ajmeese7** [comment] 2022-04-17 14:58
Note that the `spicetify-easyinstall` workaround does not help Linux users

**Comment by ajmeese7** [comment] 2022-04-17 15:03
> > @ririxidev
> > I would love to give more logs but I can't upgrade spotify from the official repos [spotify.com/us/download/linux](https://www.spotify.com/us/download/linux/) from here
> > Should I install spotify with snap then? Or are there other repos for debian that provide latest versions, I can't find those...
> 
> ```shell
> curl -sS https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg | sudo apt-key add - 
> echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
> ```
> 
> It should have the at least version 1.80 in repo. ![image](https://user-images.githubusercontent.com/9348108/163355669-66fa240a-9ee3-4f68-ae26-69467391da0f.png) If not, get deb from [here](http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.80.699.gc3dac750_amd64.deb)

The issue here is if your system runs `i386`, the `amd64` is not detected and hence version `1.1.72.439` is downloaded and this problem occurs. For future reference in case anyone else runs into this issue, do as @ririxidev suggested and manually download the `.deb` from the link they provided :)

**Comment by ririxidev** [comment] 2022-04-17 15:15
> The issue here is if your system runs i386
it can't if it isn't 32bit system installed.

**Comment by ajmeese7** [comment] 2022-04-17 15:24
I'm running a 64 bit OS (Zorin) and my client downloaded the `i386` version

**Comment by ririxidev** [comment] 2022-04-17 15:27
> I'm running a 64 bit OS (Zorin) and my client downloaded the `i386` version

Then it's distro bug it seems.

**Comment by ajmeese7** [comment] 2022-04-20 01:48
Regardless, others have experienced the issue, so it is beneficial to give an explanation for why the problem is occurring in addition to the fix :)

**Comment by ririxidev** [comment] 2022-04-20 05:04
Not saying no, just saying why your apt downloads i386 version instead of amd64.

**Comment by insidiousthedev** [comment] 2022-04-20 15:09
this happened to me too, i just reinstalled spotify (and spicetify) and it seems to work

**Comment by Flame116** [comment] 2022-04-20 15:52
Is it possible to block auto-update spotify on windows?

**Comment by xerta555** [comment] 2022-04-20 16:00
> Is it possible to block auto-update spotify on windows?

Block updates :
del %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R

**Comment by MarioK17** [comment] 2022-04-21 19:42
I confirm, It was autommaticaly downloading spotify version 1.72 (Pop os), manually downloading the last version works.

**Comment by sph3** [comment] 2022-04-22 02:45
Any way to d

> > Is it possible to block auto-update spotify on windows?
> 
> Block updates : `del %localappdata%\Spotify\Update` `mkdir %localappdata%\Spotify\Update` `icacls %localappdata%\Spotify\Update /deny "%username%":D` `icacls %localappdata%\Spotify\Update /deny "%username%":R`

Is there any way to download an older version without using a third-party site?

**Comment by xerta555** [comment] 2022-04-22 06:24
> > Block updates : `del %localappdata%\Spotify\Update` `mkdir %localappdata%\Spotify\Update` `icacls %localappdata%\Spotify\Update /deny "%username%":D` `icacls %localappdata%\Spotify\Update /deny "%username%":R`
> 
> Is there any way to download an older version without using a third-party site?

- Choose the old version you want: https://www.spotify.com/us/opensource/
- Get LoaderSpot.bat from [amd64fox repo](https://github.com/amd64fox/LoaderSpot)
- Copy-past the download link in any browser to download the version you want
- Install it
- Done.

**Comment by RazerFlick** [comment] 2022-04-22 11:43
Same blank screen for spicetify v2.9.5

**Comment by fawnyeo** [comment] 2022-04-22 20:26
was working well just before i upgraded to spicetify v2.9.6. it just keeps showing the load icon. connectivity isnt an issue here

**Comment by Daksh777** [comment] 2022-04-23 03:51
Seems like the issue is fixed with v2.9.6 for me.

**Comment by xerta555** [comment] 2022-04-23 13:58
> Seems like the issue is fixed with v2.9.6 for me.

It works again with the last fix/version yeah.

**Comment by insidiousthedev** [comment] 2022-04-23 16:49
I can confirm it works with the latest version.

**Comment by dheerajpv** [comment] 2022-04-23 17:14
It's not working for me even with the new release. (Spotify 1.1.83.956.gbe7ea9a7 / Spicetify 2.9.6)

**Comment by ririxidev** [comment] 2022-04-23 17:16
> It's not working for me even with the new release. (Spotify 1.1.83.956.gbe7ea9a7 / Spicetify 2.9.6)

Try deleting Backup folder from `.spicetify`, reinstall Spotify and do `spicetify backup apply` should work.

**Comment by dheerajpv** [comment] 2022-04-23 17:42
> > It's not working for me even with the new release. (Spotify 1.1.83.956.gbe7ea9a7 / Spicetify 2.9.6)
> 
> Try deleting Backup folder from `.spicetify`, reinstall Spotify and do `spicetify backup apply` should work.

It's working now, thanks!

**Comment by ririxidev** [comment] 2022-04-24 20:54
Closing since issue has been fixed. If some of you still experience some issues about blank screen, please try this https://github.com/spicetify/spicetify-cli/issues/1577#issuecomment-1107536930 and if it doesn't help, write here 😃

**Closed by ririxidev** 2022-04-24 20:54 UTC
Labels: 🐛 bug
