### ISSUE TITLE
I'd like it so it automatically opens to the spicetify variant instead of plain ol' spotify

### ISSUE THREAD

**Issue by CrackedSuninRise** [spicetify/spicetify-cli#2017] opened 2022-11-21 05:47 UTC
### 📝 Provide a description of the new feature

Either a new shortcut to the start menu, or a change to the existing spotify shortcut in the start menu that opens spicetify directly

**Comment by kyrie25** [comment] 2022-11-21 05:49
Duplicate of #1743

**Closed by kyrie25** 2022-11-21 05:49 UTC
