### ISSUE TITLE
Black screen for the new official AUR spotify version

### ISSUE THREAD

**Issue by neondeex** [spicetify/spicetify-cli#1466] opened 2022-02-07 20:29 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: 
Spotify version 1.1.72.439.gc253025e, Copyright (c) 2021, Spotify Ltd
- Spicetify version:
2.8.4

Manjaro OS
```

### 📝 Description

When I run spicetify apply with Comfy-spicetify theme I just get this screen

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/30392593/152866563-0cbc71f9-af2a-46e3-9589-9f65fd81d5ce.png)

**Comment by afonsojramos** [comment] 2022-02-08 01:37
Please update Spotify and Spicetify. Unfortunately, we cannot support old versions of Spotify due to the constant changing of the CSS classes and Regex changes required.

**Comment by iDCoded** [comment] 2022-02-09 03:49
I am having the same issue with **Spicetify**.
I am using the *Dribbblish* Theme, and I just get a blank screen.

**Comment by neondeex** [comment] 2022-02-09 14:08
Yes you need to update spotify to last version so use flatpak to install but dribblis does not support at the full the most new version but it will work at least

**Comment by afonsojramos** [comment] 2022-02-09 14:23
So, the issue is fixed @neondeex? Can you close the issue if so?

**Closed** 2022-02-28 00:14 UTC
Labels: 🐛 bug
