### ISSUE TITLE
lyrics from lyricstranslate

### ISSUE THREAD

**Issue by MeanXBeam** [spicetify/spicetify-cli#2073] opened 2022-12-28 04:14 UTC
### 📝 Provide a description of the new feature

have a button for lyrics from lyricstranslate as some songs i listen to have no lyrics from genius or musixmatch

### ➕ Additional Information

https://lyricstranslate.com/

**Comment by kyrie25** [comment] 2022-12-28 04:16
Duplicate of #1935

**Closed by kyrie25** 2022-12-28 04:16 UTC
Labels: 🔴 custom app
