### ISSUE TITLE
Spicetify Virus

### ISSUE THREAD

**Issue by RazerFlick** [spicetify/spicetify-cli#2099] opened 2023-01-13 11:33 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.2.582.gfae9c59b
- Spicetify version: v2.16.0
```

### 📝 Description

Unable to run spicetify.exe
Potential virus suspect...ive tried to turn off windows defender still the same errors

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/93324953/212311050-2c22ea1a-02e9-4501-a3ea-40cbe2bd7429.png)
![image](https://user-images.githubusercontent.com/93324953/212311055-df179c80-4d26-4559-956c-17a2cf4b23a0.png)

**Comment by kyrie25** [comment] 2023-01-13 11:40
Duplicate of #2098.

Do not open another identical issue after you have made one already.

**Closed by kyrie25** 2023-01-13 11:40 UTC
Labels: 🐛 bug, 🪟 windows
