### ISSUE TITLE
Error: Spotify for Windows 1.1.85.895.g2a71e1b8

### ISSUE THREAD

**Issue by y0himba** [spicetify/spicetify-cli#1668] opened 2022-05-13 10:33 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.85.895.g2a71e1b8
- Spicetify version: 2.9.8

Windows 10, latest patches. Intel i9-9900k.
```

### 📝 Description

Woke up this morning and restarted my computer.  Spotify updated. Did backup and apply. Got this error. No color or web extensions were applied. 

`C:\Users\y0himba>spicetify restore backup apply
spicetify v2.9.8
info spicetify up-to-date
warning Spotify version and backup version are mismatched.
info Spotify is at stock state. Run "spicetify backup" to backup current Spotify version.
Continue restoring anyway? [y/N] n

C:\Users\y0himba>spicetify backup
spicetify v2.9.8
info spicetify up-to-date
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
OK
OK
success Everything is ready, you can start applying now!

C:\Users\y0himba>spicetify apply
spicetify v2.9.8
info spicetify up-to-date
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error cannot find symbol for Custom app React Element
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp.func1({0xc000794000, 0x18aa98})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:220 +0x987
github.com/spicetify/spicetify-cli/src/utils.ModifyFile({0xc000010d80, 0x3a}, 0xc0001498d8)
        /home/runner/work/spicetify-cli/spicetify-cli/src/utils/utils.go:191 +0x7b
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp({0xc000010d80, 0x3d}, {{0xc000024640, 0x3, 0x4}, {0xc000024680, 0x3, 0x4}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:188 +0x90
github.com/spicetify/spicetify-cli/src/apply.AdditionalOptions({0xc00000ec30, 0x2d}, {{0xc000024640, 0x3, 0x4}, {0xc000024680, 0x3, 0x4}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:37 +0x4c3
github.com/spicetify/spicetify-cli/src/cmd.Apply({0x131b7f8, 0x5})
        /home/runner/work/spicetify-cli/spicetify-cli/src/cmd/apply.go:72 +0x9ae
main.main()
        /home/runner/work/spicetify-cli/spicetify-cli/spicetify.go:225 +0x77b`

**Comment by ririxidev** [comment] 2022-05-13 10:36
Duplicate of #1660

**Closed by ririxidev** 2022-05-13 10:36 UTC
Labels: 🐛 bug, 🔴 custom app, 🔵 extension
