### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by knightmob** [spicetify/spicetify-cli#2027] opened 2022-11-26 05:01 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.1.99.878.g1e4ccc6e
- Spicetify version: latest
```

### 📝 Description

Hello, I bump on this site yesterday, and to be honest this looks cool, but here lies the problem. I am having problem on installing spicefy in my Spotify, I tried the windows power shell method not once but many times, and it's still not working. hopefully you can assist me with my problems. here I'll send the SS for evidence.

### 📸 Screenshots

![2022-11-26_12-34](https://user-images.githubusercontent.com/76065610/204072880-97ff9da6-cbc2-4495-934f-542cf6582ab7.png)

**Comment by kyrie25** [comment] 2022-11-26 05:45
Duplicate of #418

**Closed by kyrie25** 2022-11-26 05:45 UTC
Labels: 🐛 bug, 🪟 windows
