### ISSUE TITLE
Lyrics not showing

### ISSUE THREAD

**Issue by VictorCunillera** [spicetify/spicetify-cli#2841] opened 2024-02-16 00:25 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bits)
1.2.31.1205.g4d59ad7c
Spicetify v2.31.3
```

### 📝 Description

I've been using lyrics plus for a while now, and now whenever I try to open the lyrics nothing shows up in any section.
See it in the picture.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/94693125/53858837-1962-4a76-a78b-62b421509558)

**Comment by ohitstom** [comment] 2024-02-16 00:27
known issue, riri keeps closing issues prematurely but hopefully this one stays open so it can be tracked / fixed by other individuals

**Comment by VictorCunillera** [comment] 2024-02-16 00:34
so i can't see how to solve it?

**Comment by ohitstom** [comment] 2024-02-16 01:07
> so i can't see how to solve it?

you can downgrade Spotify for now, but until then nothing can be done

**Comment by WenchenWang** [comment] 2024-02-16 02:48
same problem, waiting for solution

**Comment by ohitstom** [comment] 2024-02-16 03:31
> > > so i can't see how to solve it?
> > 
> > 
> > you can downgrade Spotify for now, but until then nothing can be done
> 
> can you tell how to downgrade spicetify?

https://github.com/ohitstom/spicetify-easyinstall/

working on fixing my installer, will be done in a day or two and i'll let you know
if you dont want to wait install 2.30 from https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=803394557
then google how to block spotify updates
then run spicetify backup apply

**Comment by ani9730** [comment] 2024-02-16 03:41
> > > > so i can't see how to solve it?
> > > 
> > > 
> > > you can downgrade Spotify for now, but until then nothing can be done
> > 
> > 
> > can you tell how to downgrade spicetify?
> 
> https://github.com/ohitstom/spicetify-easyinstall/
> 
> working on fixing my installer, will be done in a day or two and i'll let you know if you dont want to wait install 2.30 from https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=803394557 then google how to block spotify updates then run spicetify backup apply
The bat file in the link is showing an error

**Comment by rxri** [comment] 2024-02-16 05:02
Duplicate of https://github.com/spicetify/spicetify-cli/issues/2837

**Closed by rxri** 2024-02-16 05:02 UTC
Labels: 🐛 bug, 🔴 custom app
