### ISSUE TITLE
what happened?my lyrics....

### ISSUE THREAD

**Issue by WenchenWang** [spicetify/spicetify-cli#2420] opened 2023-06-19 07:04 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: V2.20.1
- Spicetify version:0.8.6
```

### 📝 Description

![Snipaste_2023-06-19_15-02-26](https://github.com/spicetify/spicetify-cli/assets/54831037/0c930c51-43d4-43bb-b145-44b1c2fa5fc1)
Lyrics position is not displayed correctly

### 📸 Screenshots

![Snipaste_2023-06-19_15-02-26](https://github.com/spicetify/spicetify-cli/assets/54831037/9f97cb72-97c7-44b2-bcde-48e0e9d52260)
Lyrics position is not displayed correctly

**Comment by WenchenWang** [comment] 2023-06-19 07:23
![Snipaste_2023-06-19_15-23-11](https://github.com/spicetify/spicetify-cli/assets/54831037/f404c643-10f8-4d4e-8678-16d2ac2ea076)
default theme

**Comment by kyrie25** [comment] 2023-06-19 07:38
Duplicate of #2416

**Closed by kyrie25** 2023-06-19 07:38 UTC
Labels: 🐛 bug
