### ISSUE TITLE
Dosen't save on spotify restart

### ISSUE THREAD

**Issue by LakkAnon** [spicetify/spicetify-cli#2489] opened 2023-07-27 12:37 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Newest
- Spicetify version: V2.22.1
```

### 📝 Description

When restarting spotify the theme dosen't save.

**Comment by kyrie25** [comment] 2023-07-27 12:42
Duplicate of #1743

**Closed by kyrie25** 2023-07-27 12:42 UTC
Labels: 🐛 bug
