### ISSUE TITLE
lyrics-plus not working right now

### ISSUE THREAD

**Issue by sherzed** [spicetify/spicetify-cli#2849] opened 2024-02-17 18:30 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205
- Spicetify version: 2.31.3
```

### 📝 Description

Lyrics-plus not working. Does not show lyrics of any song

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/42775426/f56dc4ea-3e8b-477a-a2a3-9e49490b0727)

**Comment by sherzed** [comment] 2024-02-17 18:31
Karaoke, synced, unsynced, genius. None of them work

**Comment by rxri** [comment] 2024-02-17 18:33
Duplicate of https://github.com/spicetify/spicetify-cli/issues/2844

**Closed by rxri** 2024-02-17 18:33 UTC
Labels: 🐛 bug, 🔴 custom app
