### ISSUE TITLE
spicetify full app display error

### ISSUE THREAD

**Issue by siirul** [spicetify/spicetify-cli#2440] opened 2023-06-27 04:56 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Spicetify version: 2.20.2
```

### 📝 Description

when I use the full app the display becomes like that. It happened after I updated spicetify

### 📸 Screenshots

![image_2023-06-27_115151918](https://github.com/spicetify/spicetify-cli/assets/137859435/7c0af95a-0e45-464e-b289-0bf4993bb436)

**Comment by kyrie25** [comment] 2023-06-27 04:59
Duplicate of #2435

**Comment by kyrie25** [comment] 2023-06-27 04:59
Disable `Genius` as a provider in Lyrics Plus and try again.

**Closed by kyrie25** 2023-06-27 04:59 UTC
Labels: 🐛 bug, 🔵 extension

**Comment by siirul** [comment] 2023-06-27 05:29
> Outdated Spotify version.
> 
> Disable `Genius` as a provider in Lyrics Plus and try again.
> 
> If not then update Spotify & reinstall Spicetify.

thank you it worked
