### ISSUE TITLE
the page is just plank dk what to do after update 

### ISSUE THREAD

**Issue by NOT-Kimo** [spicetify/spicetify-cli#2867] opened 2024-02-27 22:02 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: the latest i think i just updated
- Spicetify version:v2.32.1
```

### 📝 Description

cant use spotify using spictify

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/161527952/a0e44e67-a79c-4440-be02-000206964761)

**Comment by rxri** [comment] 2024-02-27 22:04
Duplicate of https://github.com/spicetify/spicetify-cli/issues/2861

**Closed by rxri** 2024-02-27 22:04 UTC
Labels: 🐛 bug

**Comment by NOT-Kimo** [comment] 2024-02-27 22:17
@rxri tried all what was there but still cant fix is there any solution soon i am still new to it kinda so a kinda detailed help would be great
