### ISSUE TITLE
[custom apps] synced romanized lyrics sometimes not syncing with current song

### ISSUE THREAD

**Issue by Oiko78** [spicetify/spicetify-cli#2749] opened 2024-01-05 15:11 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.26.1187.g36b715a1
- Spicetify version: 2.29.1
```

### 📝 Description

synced romanized lyrics not updating after clicking next and prev song

### track 1
![image](https://github.com/spicetify/spicetify-cli/assets/70620781/d2b1ce89-97f9-4da5-9d35-9c8226abe47a)
lyric is match with current track

### track 2
![image](https://github.com/spicetify/spicetify-cli/assets/70620781/0bac2bf4-1d13-40e2-ba4b-e836aa0df90c)
lyric is not match with current track after clicking next track.
lyric is for track 1

### track 3
![image](https://github.com/spicetify/spicetify-cli/assets/70620781/78372787-ca14-4c8b-9d0a-2b6257815366)
lyric is not match with current track after clicking next track.
lyric is for track 2

![image](https://github.com/spicetify/spicetify-cli/assets/70620781/f65c23aa-dc50-4820-847b-3f8e8dcdcc53)
lyric is not match with current track after clicking previous track.
lyric is for track 2

**Comment by rxri** [comment] 2024-01-10 13:25
I cannot reproduce your issue on my end. It works just fine, reloads the lyrics whenever it needs to

**Comment by Oiko78** [comment] 2024-01-10 15:50
> I cannot reproduce your issue on my end. It works just fine, reloads the lyrics whenever you do it

have you tried it with japanese songs?

**Comment by ohitstom** [comment] 2024-01-19 20:58
> > cannot reproduce your issue on my end. It works just fine, reloads the lyrics whenever you do it
> 
> I used the same songs as you. It works as expected (reloads and fetches new lyrics when skipping to next song)

i just had this same thing happen as im typing this, refuses to load the lyrics for the correct song, seems one song out of sync

**Comment by catb0x** [comment] 2024-01-20 09:44
happens to me as well but now the lyrics js arent romanized anymore

**Comment by ohitstom** [comment] 2024-01-20 12:51
> happens to me as well but now the lyrics js arent romanized anymore

yeah i doubt this issue is limited to only romanized content since that is just display options, some sort of internal logic must be breaking or not being queued properly.

I believe we had a similar issue to this in the past and it was an unnecessary use of await somewhere

**Comment by rxri** [comment] 2024-01-20 14:23
No one reverted anything. It's still without await. https://github.com/spicetify/spicetify-cli/blob/9b1afc8e70264e7b1eb962d53241fb6816cf4450/CustomApps/lyrics-plus/index.js#L550

**Comment by ohitstom** [comment] 2024-01-21 10:13
> No one reverted anything. It's still without await.
> 
> https://github.com/spicetify/spicetify-cli/blob/9b1afc8e70264e7b1eb962d53241fb6816cf4450/CustomApps/lyrics-plus/index.js#L550

wasnt trying to point fingers! was just an assumption on my end, are you still unable to replicate? the key is to go back and forward a few times ive found

**Comment by rxri** [comment] 2024-02-02 16:24
> > No one reverted anything. It's still without await.
> > https://github.com/spicetify/spicetify-cli/blob/9b1afc8e70264e7b1eb962d53241fb6816cf4450/CustomApps/lyrics-plus/index.js#L550
> 
> wasnt trying to point fingers! was just an assumption on my end, are you still unable to replicate? the key is to go back and forward a few times ive found

I cannot reproduce this issue even with going back and forward multiple times. I was doing it slowly and as fast as I can, and lyrics always changed

**Comment by Oiko78** [comment] 2024-02-26 07:17
> > > No one reverted anything. It's still without await.
> > > https://github.com/spicetify/spicetify-cli/blob/9b1afc8e70264e7b1eb962d53241fb6816cf4450/CustomApps/lyrics-plus/index.js#L550
> > 
> > 
> > wasnt trying to point fingers! was just an assumption on my end, are you still unable to replicate? the key is to go back and forward a few times ive found
> 
> I cannot reproduce this issue even with going back and forward multiple times. I was doing it slowly and as fast as I can, and lyrics always changed. Though this issue may be related to the performance of your pc 🤷‍♀️

rather than related to performance of the pc, how about network performance? because i have a relatively slow network that is around 10mbps. I have also tested it with 2 of my devices within the same network  but still encountered the same problem

**Comment by rxri** [comment] 2024-03-30 15:15
Okay so, unless I get performance report that I will give instructions now on how to make it and export,  I will close this issue since I cannot reproduce it.

How to make a performance report:
1. Run `spicetify enable-devtools` in terminal
2. Open up devtools by right clicking anywhere on Spotify, and then click on `Inspect Element`
3. Go to `Performance` tab, and click first button to the left (next to refresh button) to start recoding
4. Now, reproduce the issue by going back and forth while being in lyrics-plus
5. When you can reproduce it at least twice (will be easier to see) in the same session, pause the recording by clicking the same button, then click this button:
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/dea3d454-8c3c-486e-a614-5c2f9ccbfca4)
6. Save it somewhere and send the report here so I can take a look on that

**Comment by Oiko78** [comment] 2024-04-18 17:06
> Okay so, unless I get performance report that I will give instructions now on how to make it and export, I will close this issue since I cannot reproduce it.
> 
> How to make a performance report:
> 
> 1. Run `spicetify enable-devtools` in terminal
> 2. Open up devtools by right clicking anywhere on Spotify, and then click on `Inspect Element`
> 3. Go to `Performance` tab, and click first button to the left (next to refresh button) to start recoding
> 4. Now, reproduce the issue by going back and forth between songs while staying on lyrics-plus page
> 5. When you can reproduce it at least twice (will be easier to see) in the same session, pause the recording by clicking the same button, then click this button:
>    ![image](https://private-user-images.githubusercontent.com/9348108/318204757-dea3d454-8c3c-486e-a614-5c2f9ccbfca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTkzMDgsIm5iZiI6MTcxMzQ1OTAwOCwicGF0aCI6Ii85MzQ4MTA4LzMxODIwNDc1Ny1kZWEzZDQ1NC04YzNjLTQ4NmUtYTYxNC01YzJmOWNjYmZjYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMTY1MDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGEzOTc2OGQwZGIyNDYxOWNiYmZiYzYxNmIxMTM0YWUxMGM5OWVmODM0M2Q5NDc0OTdmMTFjNDQyZWM2MWEzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DZ67yx20iD6YlF4SDg_73y1tW1cdCFidSzrh596Fgs8)
> 6. Save it somewhere and send the report here so I can take a look on that

Please check the performance report here.
[Trace-20240418T235613.json.zip](https://github.com/spicetify/spicetify-cli/files/15028062/Trace-20240418T235613.json.zip)

I start with lyric-plus opened, then start playing first track and the lyric is still fine. but after clicking next track, lyric is not synced

**Comment by ak8000** [comment] 2024-04-21 23:17
I had the same issue and came tracking open issues for this. Not really sure why, as when I try to reproduce it again, everything is as normal.

**Comment by ohitstom** [comment] 2024-04-24 21:04
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/0c70eca0-5aa9-4a1c-8cbe-a8471d6b385b)
this error cropped up after a few instances of becoming unsynced all though this error doesnt always show up

**Closed** 2024-04-30 01:28 UTC
Labels: 🐛 bug, ❓ help wanted, 🔴 custom app
