### ISSUE TITLE
I've had this weird bug while using Shuffle+ for a while now 

### ISSUE THREAD

**Issue by NotARegularOTAKU** [spicetify/spicetify-cli#1839] opened 2022-07-26 06:53 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.90.859.gf1bb1e36
- Spicetify version: 2.11.1
```

### 📝 Description

Whenever I go to my playlist and hit play with shuffle+, it does do what its meant to do and shuffles the playlist properly but when I click on the track that's currently playing so that it'll take me to where the track is in my playlist, all it does it take me to my playlist's page if I wasn't already on it and if I was already on it then it does nothing.

**Comment by kyrie25** [comment] 2022-07-26 08:20
Not a bug, nor related to Shuffle+. Closing issue.

**Closed by kyrie25** 2022-07-26 08:20 UTC
Labels: 🐛 bug, 🔵 extension
