### ISSUE TITLE
Spicetify install issue

### ISSUE THREAD

**Issue by buckbafalo** [spicetify/spicetify-cli#2102] opened 2023-01-14 13:03 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:latest one (as of making this issue)
- Spicetify version:i cant download spicetify
```

### 📝 Description

I've been trying to get Spicetify to install for a while now, it keeps bringing up this error.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/51851969/212472737-ed3bc790-4ffc-4d2d-bbdf-6d8a47e6a24a.png)

**Comment by kyrie25** [comment] 2023-01-14 14:52
Duplicate of #2098

**Closed by kyrie25** 2023-01-14 14:52 UTC
Labels: 🐛 bug

**Comment by buckbafalo** [comment] 2023-01-14 15:12
> Duplicate of #2098

Oh, I didn't see that one, my bad I'll take this down
