### ISSUE TITLE
New releases does not load

### ISSUE THREAD

**Issue by Horrid-12** [spicetify/spicetify-cli#2694] opened 2023-11-30 16:32 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.25.1011. g0348b2ea
- Spicetify version: 2.72.2
```

### 📝 Description

The new releases tab does not load, facing this since last update and faced it in past once 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/96373496/287bb884-b881-42fa-8b32-fd6d06933a7c)

**Comment by rxri** [comment] 2023-11-30 16:36
Check the note in https://github.com/spicetify/spicetify-cli/releases/tag/v2.27.2, plus duplicate of #2678

**Closed by rxri** 2023-11-30 16:36 UTC
Labels: 🐛 bug, 🔴 custom app
