### ISSUE TITLE
[Popup Lyrics] Lyrics freeze when window goes out of focus

### ISSUE THREAD

**Issue by zubairmh** [spicetify/spicetify-cli#2935] opened 2024-04-01 18:34 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.33.1042.g26c92729
- Spicetify version: 2.35.1
```

### 📝 Description

1) Install the popup lyrics extension
2) Play a song
3) Click on the popup lyrics icon and wait for the lyrics to load
![image](https://github.com/spicetify/spicetify-cli/assets/116816535/b83449b2-7a46-4e3a-b29e-434becdf72e2)
4) Lose focus of the main Spotify Window by switching to another application
5) The lyrics freeze immediately the window goes out of focus and refuse to go back to sync even when the song is changed.

**Extra Details/Theories:**
- Hardware Acceleration is enabled
- I'm assuming Windows is suspending the main renderer, causing some part of [this function](https://github.com/spicetify/spicetify-cli/blob/29fc298f6875151e323e7ba726e1f0b0a0c77be7/Extensions/popupLyrics.js#L699) to fail.

### 📸 Screenshots

**When the extension is opened with the window focused**
![image](https://github.com/spicetify/spicetify-cli/assets/116816535/97644292-74bf-4c20-8ec1-69c21c5c202b)

**Post Switching Windows** (frozen & out of sync):
![image](https://github.com/spicetify/spicetify-cli/assets/116816535/046d903b-b0c2-463e-9622-af482bcfa22e)

**Comment by rxri** [comment] 2024-04-01 18:47
I cannot reproduce it to this day. Duplicate of https://github.com/spicetify/spicetify-cli/issues/2827
ServiceWorker works as expected. The line you provided is executed by https://github.com/spicetify/spicetify-cli/blob/master/Extensions/popupLyrics.js#L18

**Closed by rxri** 2024-04-01 18:47 UTC
Labels: 🐛 bug, 🔴 custom app, 🔵 extension
