### ISSUE TITLE
Changing theme color scheme in app causes the "Something went wrong" screen to appear

### ISSUE THREAD

**Issue by Miki200v2** [spicetify/spicetify-cli#1562] opened 2022-03-30 12:33 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.81.604.gccacfc8c
- Spicetify version:2.9.2
```

### 📝 Description

Apply any theme with color schemes via the marketplace, then attempt to change the color scheme, you should get this screen
![image](https://user-images.githubusercontent.com/38375126/160835177-ffaf4003-d3e7-4c42-8ea6-4fa14fd44f80.png)

**Comment by theRealPadster** [comment] 2022-04-09 05:59
1. This is related to [Marketplace](https://github.com/spicetify/spicetify-marketplace), not Spicetify itself. 
2. It's caused by the menu hook being broken and has been fixed in the latest Spotify + Spicetify version.

**Closed by theRealPadster** 2022-04-09 05:59 UTC
Labels: 🐛 bug
