### ISSUE TITLE
[Full App Display] LyricsPlus Integration is too far on the right

### ISSUE THREAD

**Issue by lupus0802** [spicetify/spicetify-cli#2433] opened 2023-06-24 09:57 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.14.1149.ga3ae422d
- Spicetify version: v2.20.1
- Operating System: Windows 10 22H2
```

### 📝 Description

I'm experiencing this issue after upgrading both Spotify and Spicetify to the newest version. 

- Play any song
- Start FAD
- Enable LyricsPlus Integration

The Lyrics (or the no lyrics found sign) are located on the right edge of the screen, maybe because the other information is "pushing" the Lyrics block to the right (it would at least make sense looking at the symmetry).

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/87112805/3c6a11ce-7724-4870-9c8e-e170df6a5ea0)

You can see a bit of the lyrics information on the right. 
Note: The height of the text is perfectly fine, it simply seems off at the moment even though that is not the case.

**Comment by kyrie25** [comment] 2023-06-24 09:58
Duplicate of #2416

**Closed by kyrie25** 2023-06-24 09:58 UTC
Labels: 🐛 bug, 🔴 custom app

**Comment by lupus0802** [comment] 2023-06-24 11:41
Thanks for the info and sorry about that - couldn't find that issue with the keywords I gave the filter apparently.

**Comment by WenchenWang** [comment] 2023-06-26 01:50
Have you solved it? I still haven't solved the location problem

**Comment by lupus0802** [comment] 2023-06-26 05:50
No, it will be included in the next release though as they seem to have fixed it in the other issue (the pull request was completed after the last release).

**Comment by iojkn** [comment] 2023-07-01 14:39
still weired now

**Comment by lupus0802** [comment] 2023-07-01 22:07
Issue has been fixed for me, make sure to upgrade spicetify
