### ISSUE TITLE
[Popup Lyrics] When spotify minimized window, Using CPU and memory more than usual

### ISSUE THREAD

**Issue by frallatta** [spicetify/spicetify-cli#2807] opened 2024-02-07 06:46 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.30.1135.g02fef27a
Spicetify v2.31.0
Theme: Comfy / Comfy
Extensions: popuplyricsplus.js, popuplyrics.js, romaji_lyrics.js, theme.js
Custom apps: marketplace, lyrics-plus
```

### 📝 Description

Popup Lyrics using more CPU and Memory when spotify on minimized window.
and when "No Lyrics" found in song then CPU and memory will go up till 100% and spotify freezing.
please look at the video how to reproduce the issue.

Issue were found when discussing with @Patrick-orz

https://github.com/spicetify/spicetify-cli/assets/103402135/3d87c516-8481-40b6-a08d-87ff81793692

**Comment by rxri** [comment] 2024-02-07 11:28
This doesn't seem like spicetify or PopupLyrics related. Code for it was made ages ago and no one to this day didn't found any issues with it, neither can I right now. Basically, I cannot reproduce your issue meaning that the issue probably doesn't come from this extension. I will be more happy to help when you will provide us with Performance report, however at this moment since I cannot reproduce this issue - I'm closing this issue (and yes, I was trying to reproduce it like you shown in the video)

**Closed** 2024-02-08 00:44 UTC
Labels: 🐛 bug, 🔴 custom app, 🔵 extension
