### ISSUE TITLE
lyrics plus refresh token buttton says "failed to refresh token"

### ISSUE THREAD

**Issue by someone12421** [spicetify/spicetify-cli#2847] opened 2024-02-16 22:17 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 2.31.3
- Spicetify version: 1.2.26.1187.g36b715a1 flatpak
```

### 📝 Description

when i try to refresh the musixmatch token on lyrics plus it says  "failed to refresh token", i tried getting a token from the musixmatch app but pressing Ctrl + Shift + i didnt work. 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/131603701/ecedbf78-f283-46ba-aec8-a9bd22b51159)

**Comment by rxri** [comment] 2024-02-16 22:19
Duplicate of #2844

**Comment by rxri** [comment] 2024-02-16 22:20
Oh, actually I noticed that you're on 1.2.26. You're probably ratelimited by musixmatch then. Wait a few minutes and try again ^^

**Closed by rxri** 2024-02-16 22:19 UTC
Labels: 🐛 bug, 🔴 custom app

**Comment by someone12421** [comment] 2024-02-16 23:05
might actually be running a different version. I can't find a way to check the version inside of the Linux app so I copied it from what was listed as the version in flathub but I retried refreshing the token multiple times and it still didn't work so it sounds more like #2844

**Comment by rxri** [comment] 2024-02-16 23:30
The #2844 issue is only a thing on 1.2.31 which isn't released on linux yet

**Comment by someone12421** [comment] 2024-02-16 23:33
Oh, I'll try again tomorrow then. It's 1 am for me so I should probably go to sleep lol.
