### ISSUE TITLE
f key breaks all buttons

### ISSUE THREAD

**Issue by UreshiiPanda** [spicetify/spicetify-cli#2866] opened 2024-02-27 21:28 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.17
- Spicetify version: 2.32.1
- MacOS 13.4
```

### 📝 Description

with keyboardShortcut.js installed, when the f key is pressed all buttons on Spotify become unclickable and are not detected/recognized as buttons by the cursor, and no button navigation tags appear. Devtools screenshot has been included.

### 📸 Screenshots

<img width="1019" alt="Screenshot 2024-02-27 at 3 57 45 PM" src="https://github.com/spicetify/spicetify-cli/assets/39992411/5fb0151a-4843-4914-87e2-e20570675eb6">

**Comment by rxri** [comment] 2024-02-27 21:38
Duplicate of https://github.com/spicetify/spicetify-cli/issues/2857#issuecomment-1962422102

**Closed by rxri** 2024-02-27 21:38 UTC
Labels: 🐛 bug
