### ISSUE TITLE
Lyrics Plus config Not working

### ISSUE THREAD

**Issue by ani9730** [spicetify/spicetify-cli#2843] opened 2024-02-16 03:27 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.31.3
```

### 📝 Description

When i updated spicetify, LyricsPlus stopped working.

### 📸 Screenshots

<img width="1276" alt="Screenshot 2024-02-16 085603" src="https://github.com/spicetify/spicetify-cli/assets/120796659/a9dd0281-e0e7-4f15-9e05-c3a8cc53064d">

**Comment by rxri** [comment] 2024-02-16 05:02
Duplicate of https://github.com/spicetify/spicetify-cli/issues/2837

**Closed by rxri** 2024-02-16 05:02 UTC
Labels: 🐛 bug
