### ISSUE TITLE
[Lyrics Plus] Link the old lyrics button to lyrics plus

### ISSUE THREAD

**Issue by Yashirow** [spicetify/spicetify-cli#2146] opened 2023-02-09 16:08 UTC
### 📝 Provide a description of the new feature

When clicking on the bottom lyrics button with the lyrics plus page open it close it but when it's not open it redirect to the old lyrics interface.
Could it be possible to redirect the button directly to the lyrics plus page ?

**Comment by kyrie25** [comment] 2023-02-09 22:47
Duplicate of #1949

**Closed** 2023-02-09 22:47 UTC
Labels: 🔴 custom app
