### ISSUE TITLE
spicetify error

### ISSUE THREAD

**Issue by pandailluminaty** [spicetify/spicetify-cli#1602] opened 2022-04-22 18:56 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: I think the newest
- Spicetify version:v2.9.6
```

### 📝 Description

Spotify had a new update so I did a spicetify upgrade (I did all of the commands) and after Spotify don't load fully. I can listen to music but all of it is on a green screen. I used the Dribblish.js extension. I did spicetify backup, and spicetify restore, but did not help. 

### 📸 Screenshots

![Képernyőkép 2022-04-22 205544](https://user-images.githubusercontent.com/104225426/164777130-04107af1-e3e9-491c-8f80-2c4d37f50a81.jpg)

**Comment by Iridum-png** [comment] 2022-04-22 19:21
I am also having this error - uninstalling did not work. Assuming spicetify hasn't been updated yet

**Comment by ririxidev** [comment] 2022-04-22 19:37
Duplicate of https://github.com/spicetify/spicetify-cli/issues/1599, https://github.com/spicetify/spicetify-cli/issues/1577

**Closed by ririxidev** 2022-04-22 19:37 UTC
Labels: 🐛 bug, 🔴 custom app, 🔵 extension

**Comment by philipch07** [comment] 2022-04-22 20:16
No, this isn't fixed. I'm running:
```
Spotify for Windows
1.1.83.956.gbe7ea9a7
```
And my spicetify version is:
![image](https://user-images.githubusercontent.com/59272129/164787510-24ddeb6c-4e4a-4cfb-bf06-12fe38985974.png)

Running `spicetify apply` leaves me on a blank screen like many others.

**Comment by ririxidev** [comment] 2022-04-22 20:17
Remove backup folder

**Comment by philipch07** [comment] 2022-04-22 20:28
Whoops. That worked, thanks.
