### ISSUE TITLE
Context menu on New Releases

### ISSUE THREAD

**Issue by bramdsgn** [spicetify/spicetify-cli#1523] opened 2022-03-04 16:07 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.80
- Spicetify version: 2.9.2
```

### 📝 Description

I usually go to new releases and basically right click for the context menu on albums just so add them to the Queue.
Problem is, no context menu, right-clicking does nothing.

Other issues that can be related
- I also don't have the context menu (dev tools) to reload Spotify and all.
- Right Click on Marketplace items results in "Something went Wrong, reload page"
- "Power bar" extension has a Ctrl+Space shortcut to work, it doesn't do anything.

**Comment by itsmeow** [comment] 2022-03-04 22:34
Duplicate of #1514 (issue due to broken hooks)

**Closed by itsmeow** 2022-03-04 22:34 UTC
Labels: 🐛 bug, 🔴 custom app, 🔵 extension
