### ISSUE TITLE
Bookmark extension not working

### ISSUE THREAD

**Issue by AarshGajjar** [spicetify/spicetify-cli#2145] opened 2023-02-09 04:50 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.4.912.g949d5fd0
- Spicetify version: 2.16.0
```

### 📝 Description

The topbar button for the bookmark extension is not showing after the spotify update. I downgraded to Spotify 1.2.2.582 and it works on that version.

**Comment by kyrie25** [comment] 2023-02-09 06:20
Duplicate of #2144

**Comment by kyrie25** [comment] 2023-02-09 06:21
Clearly have not checked older issues but proceed to check the box anyways lol.

**Closed by kyrie25** 2023-02-09 06:20 UTC
Labels: 🐛 bug, 🔵 extension
