### ISSUE TITLE
Spicetify not recognized in PowerShell

### ISSUE THREAD

**Issue by CalebVeinotte** [spicetify/spicetify-cli#2159] opened 2023-02-17 17:09 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.2.5.1006.g22820f93
- Spicetify version: v2.16.1
```

### 📝 Description

Receiving the following error any time that I try to update, uninstall, or install spicetify when running Powershell or Powershell (x86).  

spicetify : The term 'spicetify' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ spicetify upgrade
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (spicetify:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Any ideas why or what I need to do to fix it?  Thanks

**Comment by rxri** [comment] 2023-02-17 17:58
If install script doesn't add spicetify to path, do it manually by:
- Going to `Advanced system settings`
- Clicking `Environment Variables...`
- In `User variables for me` section, edit `Path` variable
- Click `New` with `C:\Users\<your account username>\AppData\Local\spicetify`
- Save and restart Powershell. This should make `spicetify` available

**Comment by kyrie25** [comment] 2023-02-17 23:22
Duplicate of #1766

**Closed by kyrie25** 2023-02-17 23:22 UTC
Labels: 🐛 bug

**Comment by CalebVeinotte** [comment] 2023-02-19 19:31
I followed the instructions given in this post as well as the post that his was mentioned as a duplicate of, it did not solve the issue.  I cannot even uninstall spicetify according to the github in order to do a clean install.  Any other suggestions?

**Comment by kyrie25** [comment] 2023-02-21 22:51
The path has changed from what it looked like in the linked issue.

Follow the guide from the issue using the path mentioned in this post.

**Comment by CalebVeinotte** [comment] 2023-03-03 13:12
![image](https://user-images.githubusercontent.com/89270887/222728637-ec5c0b7f-5244-423d-9806-73691c60ca51.png)
This is my current path and the error is still occurring

**Comment by kyrie25** [comment] 2023-03-03 13:24
> Receiving the following error any time that I try to update, uninstall, or install spicetify

Have you even installed Spicetify?

Please show proof of you running the install scripts from our website and trying to run Spicetify in the **same** screenshot.

**Comment by CalebVeinotte** [comment] 2023-03-03 13:39
![image](https://user-images.githubusercontent.com/89270887/222734439-8eb1aad4-8e0a-46dc-985c-8dd8a114e0e7.png)

**Comment by kyrie25** [comment] 2023-03-03 13:53
Are you installing as an administrator? If so then use a normal PowerShell session and try again.

If this doesn't work then join our Discord support server and make a ticket there and our Helpers ưill assist you, since this isn't a Spicetify issue of itself but something to do with your system configuration.

**Comment by CalebVeinotte** [comment] 2023-03-03 14:00
Ok, thank you for your help and patience
