### ISSUE TITLE
New Releases custom app prevents spotify from loading

### ISSUE THREAD

**Issue by evilsh3ll** [spicetify/spicetify-cli#2674] opened 2023-11-22 07:10 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.25.1009.g075ce884
- Spicetify version: 2.27.1
I use archlinux and I installed spotify and spicetify rom AUR, then I manually installed new-releases app
```

### 📝 Description

Since the latest spotify update, the app doesn't start correctly unless I remove new-releases. I tried to fully uninstall spicetify and spotify but if removing **new-releases** is the only way to make spotify+spicetify working.

Steps to reproduce:
1. install spotify from AUR (archlinux)
2. install spicetify from AUR
3. manually add new-releases downloading it from this repository (new-releases last update is from last month)
4. edit config-xpui.ini accordingly
5. run spicetify apply
6. try to run spotify

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/63223659/e91c298f-bb7b-4165-a67e-03ca82868ed4)
**error in english**: There was a problem, please reload the page

**Comment by rxri** [comment] 2023-11-22 07:30
Duplicate of #2672

**Closed by rxri** 2023-11-22 07:30 UTC
Labels: 🐛 bug, 🐧 linux, 🔴 custom app

**Comment by evilsh3ll** [comment] 2023-11-22 08:03
How con I downgrade spotify? it's from aur :( there isn't a cache I can use with **downgrade** package. Is there an ETA for the support of the new spotify version?
