### ISSUE TITLE
Lyrics Plus prevents the app from loading

### ISSUE THREAD

**Issue by alba4k** [spicetify/spicetify-cli#2673] opened 2023-11-21 18:34 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.25.1009
- Spicetify version: 2.27.1

Arch Linux, running Hyprland
```

### 📝 Description

Spotify won't load if I have lyrics plus enabled in `config-xpui.ini`. Having everything else but LP enabled works as intended.

### 📸 Screenshots

![immagine](https://github.com/spicetify/spicetify-cli/assets/84153269/d61bd670-1e1e-4d2b-95a6-dcb589a09b5f)

**Comment by rxri** [comment] 2023-11-21 18:43
Duplicate of #2672

**Closed by rxri** 2023-11-21 18:43 UTC
Labels: 🐛 bug, 🔴 custom app
