### ISSUE TITLE
spicetify crossfade and search buttons not appearing straight after installing spicetify

### ISSUE THREAD

**Issue by jasongithub111** [spicetify/spicetify-cli#1536] opened 2022-03-18 12:05 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: not sure
- Spicetify version:not sure
```

### 📝 Description

I had just installed spicetify and was downloading extensions when I had noticed my crossfade turned off. When i tried going to settings to turn it back on the option wasn't there and the button to search through settings was also missing. This issue was reported before but there was no real fix to it.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/101873689/158999965-a54e1e44-66da-416c-9191-726e2217fce1.png)

**Comment by jasongithub111** [comment] 2022-03-18 12:07
Also I've tried 'spicetify restore' and getting rid of spicetify completly and the option is still missing even though the option was there just before I installed spicetify

**Comment by afonsojramos** [comment] 2022-03-25 15:31
Can you check again? It should be under Playback. Maybe try expanding on the "advanced settings"

**Comment by jasongithub111** [comment] 2022-03-27 10:23
i've expanded the advanced the buttons are just missing

**Comment by afonsojramos** [comment] 2022-03-28 09:24
Maybe you no longer have Spoitify Premium?

**Comment by jasongithub111** [comment] 2022-04-11 11:33
> Maybe you no longer have Spotify Premium?

Never did the options were still there

**Comment by ririxidev** [comment] 2022-04-12 17:41
After fresh install of spicetify v2.9.5, I can't reproduce the problem. Please give us steps to reproduce (with video if possible). Closing this issue for now, will re-open when get steps to reproduce.
---
Environment:
```markdown
- spotify 1.1.81.604.gccacfc8c
- Windows 11 Pro Insider Preview Build 22593.1
- spicetify v2.9.5

**Closed by ririxidev** 2022-04-12 17:41 UTC
Labels: 🐛 bug, 🔵 extension
