### ISSUE TITLE
Spicetify doesn't stay after a restart

### ISSUE THREAD

**Issue by Godeonn** [spicetify/spicetify-cli#2119] opened 2023-01-23 18:49 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.3.1115.gd61a8f5c
- Spicetify version: v2.16.0
```

### 📝 Description

Whenever I shut off my pc and turn it back on, I have to reinstall Spicetify.

**Comment by kyrie25** [comment] 2023-01-23 23:37
Duplicate of #1743

**Closed by kyrie25** 2023-01-23 23:37 UTC
Labels: 🐛 bug
