### ISSUE TITLE
spicetify term is not recognized in powershell

### ISSUE THREAD

**Issue by maxlegend-dell** [spicetify/spicetify-cli#1766] opened 2022-06-18 02:56 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 8.7.38.670
- Spicetify version: 2.10.1
```

### 📝 Description

iex : The term 'spicetify' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:2 char:106
+ ... .com/spicetify/spicetify-marketplace/main/resources/install.ps1 | iex
+                                                                       ~~~
    + CategoryInfo          : ObjectNotFound: (spicetify:String) [Invoke-Expression], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

### 📸 Screenshots

![qwqweqe](https://user-images.githubusercontent.com/63546669/174419984-35eba8b0-6b62-41e7-80a2-b69a58944a7a.png)

**Comment by kyrie25** [comment] 2022-06-18 05:18
Try manually adding `%userprofile%\spicetify-cli` to your PATH environment variable via `View advanced system settings => Advanced => Environment Variables`
![image](https://user-images.githubusercontent.com/77577746/174423966-7ec10eb1-5261-4376-bd6c-3349979c824b.png)

**Comment by kyrie25** [comment] 2022-06-18 05:23
Closing this as duplicate of #1569

**Closed by kyrie25** 2022-06-18 05:23 UTC
Labels: 🐛 bug
