### ISSUE TITLE
Unable to downlaod spicetify

### ISSUE THREAD

**Issue by riyanshlunia** [spicetify/spicetify-cli#2113] opened 2023-01-21 03:59 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest
- Spicetify version: Latest

Whenever I am trying to install spicetify I get this kind of a problem I am using a windows 11 laptop i have even tried it over a windows 10 laptop using diffrent network still it shows the same problem Look at this.


 : Unable to connect to the remote server
At line:1 char:1
+ iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/m ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

iwr : Unable to connect to the remote server
At line:2 char:1
+ iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-marke ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

### 📝 Description

I have tried almost every fix on youtube and google it shows the same error please help me out with it.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/72033389/213842412-30a2a211-a2ae-449e-9daf-a6f7165c5b23.png)

**Comment by kyrie25** [comment] 2023-01-21 04:00
Duplicate of #2072

**Comment by kyrie25** [comment] 2023-01-21 04:01
Please actually read other issues before ticking on the box.

**Closed by kyrie25** 2023-01-21 04:01 UTC
Labels: 🐛 bug, 🪟 windows
