### ISSUE TITLE
Can't Update/Reinstall spicetify 

### ISSUE THREAD

**Issue by YASUEMMNNMM** [spicetify/spicetify-cli#2502] opened 2023-08-05 06:02 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.5.1006
- Spicetify version: v2.17.2
- Windows Version: 6.1/Windows 7
```

### 📝 Description

Can't update it, can y'all tell what's the problem?
![image](https://github.com/spicetify/spicetify-cli/assets/131770372/625a5c9b-77e9-4696-a10b-91b2d7219758)

**Comment by kyrie25** [comment] 2023-08-05 06:06
Duplicate of #418

**Closed by kyrie25** 2023-08-05 06:06 UTC
Labels: 🐛 bug

**Comment by kyrie25** [comment] 2023-08-05 06:07
Issues are not for help.

Make a support ticket on Discord if you need assistance.
