### ISSUE TITLE
Spicetify 2.17.2 contain a virus?

### ISSUE THREAD

**Issue by 1maginaryNumbers** [spicetify/spicetify-cli#2261] opened 2023-04-15 03:52 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.2.9.743.g85d9593d
- Spicetify version:2.17.2
```

### 📝 Description

I can't upgrade spicetify v2.17.2 because it contains a virus. 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/104255911/232181614-5a22b7d5-121b-479e-a273-9d2b6c6a2d20.png)

**Comment by kyrie25** [comment] 2023-04-15 04:26
Duplicate of #2098

**Closed by kyrie25** 2023-04-15 04:26 UTC
Labels: 🐛 bug

**Comment by 1maginaryNumbers** [comment] 2023-04-15 04:27
thx

**Comment by kyrie25** [comment] 2023-04-15 04:28
Please **check older issues** before claiming that you have done so.
