### ISSUE TITLE
Not working in M1 Macs

### ISSUE THREAD

**Issue by Mo-Shakib** [spicetify/spicetify-cli#1910] opened 2022-09-02 00:15 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.1.92.647.ga4397eb7
- Spicetify version: v2.13.0
```

### 📝 Description

Not working in M1 Macs

Showing this error:

❯ curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh
DOWNLOADING https://github.com/spicetify/spicetify-marketplace/archive/refs/heads/dist.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 36: spicetify: command not found

### 📸 Screenshots

![Screenshot 2022-09-02 at 6 14 52 AM](https://user-images.githubusercontent.com/50780268/188033138-04db467f-7734-4c15-b97d-1ccc73418cf5.jpg)

**Comment by kyrie25** [comment] 2022-09-02 00:16
Duplicate of #1795

**Closed by kyrie25** 2022-09-02 00:16 UTC
Labels: 🐛 bug
