### ISSUE TITLE
[Popup Lyrics] turns red when I hover over it?

### ISSUE THREAD

**Issue by witchoyy** [spicetify/spicetify-cli#2199] opened 2023-03-15 20:32 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version: 2.16.2
```

### 📝 Description

I can see the lyrics just fine, but when I hover my cursor over the popup window to movie it, it turns completely red. I've checked older issues and there's only one which didn't have the solution.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/114729496/225434822-1642485a-929f-4dd7-bfc4-2be317383d85.png) ![image](https://user-images.githubusercontent.com/114729496/225434885-a27a6638-e85e-4f3e-89cc-f91f17d36966.png)

**Comment by kyrie25** [comment] 2023-03-15 22:48
Duplicate of #1827

**Closed by kyrie25** 2023-03-15 22:48 UTC
Labels: 🐛 bug, 🔴 custom app
