### ISSUE TITLE
Spicetify.addToQueue not working

### ISSUE THREAD

**Issue by Tetrax-10** [spicetify/spicetify-cli#1891] opened 2022-08-25 16:16 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.92.647.ga4397eb7
- Spicetify version: 2.12.0
```

### 📝 Description

```js
function shouldAdd(uri) {
    let uriObj = Spicetify.URI.fromString(uri[0]);
    switch (uriObj.type) {
        case Type.TRACK:
            return true;
    }
    return false;
}

async function addTrackToQueue(uri) {
    console.log(uri);
    await Spicetify.addToQueue(uri);
}

new Spicetify.ContextMenu.Item("Test", addTrackToQueue, shouldAdd, "heart-active").register();

```

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/75513645/186716737-18186dab-503d-42b8-93af-8d826cbefb0e.png)

**Comment by kyrie25** [comment] 2022-08-26 01:22
Not a Spicetify wrapper bug as the `addToQueue` function is just a shorthand for the actual internal Player function:
https://github.com/spicetify/spicetify-cli/blob/6c756a6de8037a4b89a4367c966ae3ea40cc1bbf/jsHelper/spicetifyWrapper.js#L217-L218

I'm guessing they forgot to bind the function to `_queue` lol
![image](https://user-images.githubusercontent.com/77577746/186796375-fcfe5cdf-986c-458e-9003-f832c2ece7b5.png)

**Comment by kyrie25** [comment] 2022-08-26 01:36
My apologies, it seems that the issue is caused because Spotify binds their functions onto the `_queue` object and will break when reassigned elsewhere.
A fix is on the way to expect it in the next release.

**Comment by Tetrax-10** [comment] 2022-08-26 07:50
Yeah it will print the function but you cant add songs to queue with this function.
If you fix this it will be great help to me.
as my [Sort-by-Play-count](https://github.com/Tetrax-10/Spicetify-Extensions/tree/master/Sort-by-Play-count) extension has a fu*ked up addToQueue implementation

**Comment by kyrie25** [comment] 2022-08-26 12:28
> as my [Sort-by-Play-count](https://github.com/Tetrax-10/Spicetify-Extensions/tree/master/Sort-by-Play-count) extension has a fu*ked up addToQueue implementation

You can use the fullhand function `Spicetify.Player.origin._queue.addToQueue` instead of the shorthand one, works the same.

**Comment by Tetrax-10** [comment] 2022-08-26 12:34
> Spicetify.Player.origin._queue.addToQueue

Does this `Spicetify.Player.origin._queue.addToQueue` work to add songs now?

**Comment by kyrie25** [comment] 2022-08-26 12:55
That and the shorthand `Spicetify.addToQueue` are literally the same function, as shown in the snippet.

**Comment by Tetrax-10** [comment] 2022-08-26 13:01
> Spicetify.addToQueue = Spicetify.Player.origin._queue.addToQueue;

Man don't think am a Stupid, I literally didn't see you have typed this code there
```js
Spicetify.addToQueue = Spicetify.Player.origin._queue.addToQueue;
```

**Comment by kyrie25** [comment] 2022-08-26 13:20
> Not a Spicetify wrapper bug as the `addToQueue` function is just a shorthand for the actual internal Player function:
> 
> https://github.com/spicetify/spicetify-cli/blob/6c756a6de8037a4b89a4367c966ae3ea40cc1bbf/jsHelper/spicetifyWrapper.js#L217-L218

@Tetrax-10 click on the URL above that I linked in my first comment here.

**Closed** 2022-09-01 15:20 UTC
Labels: 🐛 bug
