### ISSUE TITLE
Korean lyrics translation

### ISSUE THREAD

**Issue by wahyuandhikarizaldi** [spicetify/spicetify-cli#2195] opened 2023-03-13 09:28 UTC
### 📝 Provide a description of the new feature

Can you add Korean lyrics translation just like the japanese translation? So user can read the korean lyrics as romaji

**Comment by kyrie25** [comment] 2023-03-26 08:52
Duplicate of #1411 
Japanese modal **converts** Japanese lyrics into different types, it does not translate

**Closed by kyrie25** 2023-03-26 08:52 UTC
Labels: 🔴 custom app
