### ISSUE TITLE
Spicetify not recognized in PowerShell

### ISSUE THREAD

**Issue by CalebVeinotte** [spicetify/spicetify-cli#2168] opened 2023-02-21 19:07 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.2.5.1006.g22820f93
- Spicetify version:v2.16.1
```

### 📝 Description

Receiving the following error any time that I try to update, uninstall, or install spicetify when running Powershell or Powershell (x86).

spicetify : The term 'spicetify' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

spicetify upgrade
  + CategoryInfo          : ObjectNotFound: (spicetify:String) [], CommandNotFoundException
  + FullyQualifiedErrorId : CommandNotFoundException

I made sure the path was manually added according to the issues mentioned in [#1766](https://github.com/spicetify/spicetify-cli/issues/1766) but that didn't solve the issue.
Any ideas why or what I need to do to fix it? Thanks

**Comment by kyrie25** [comment] 2023-02-21 22:49
Duplicate of #2159.

Don't make duplicate issues or else risk being marked as spam.

**Closed by kyrie25** 2023-02-21 22:49 UTC
Labels: 🐛 bug
