### ISSUE TITLE
Every Time i restart my PC nothing works.

### ISSUE THREAD

**Issue by Lelooo10** [spicetify/spicetify-cli#2267] opened 2023-04-16 08:32 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
-Spotify for Windows
 1.2.9.743.g85d9593d
- Spicetify version: v2.17.2
```

### 📝 Description

After i Shutdown or restart my PC my Virtulaizer from Rainmeter such as my spotify design doesn´t work. 
I have to put all the Codes such as spicetify config extensions webnowplaying.js and spicetify backup apply to get it to work. 
I think i missed something or is it so that i have to put the code every time there?

**Comment by kyrie25** [comment] 2023-04-16 08:55
Duplicate of #1743

**Closed by kyrie25** 2023-04-16 08:55 UTC
Labels: 🐛 bug, 🔵 extension

**Comment by Lelooo10** [comment] 2023-04-16 09:00
@kyrie25 it is not the same pls make it open again. In this Ticket the person fixed it with the windows official version, but i already have it.

**Comment by kyrie25** [comment] 2023-04-16 09:12
> in this Ticket 

Issues are **not** support tickets.

> the person fixed it with the windows official version, but i already have it.

Reinstall it from their website.,
