### ISSUE TITLE
Marketplace problems

### ISSUE THREAD

**Issue by juanestragon** [spicetify/spicetify-cli#2274] opened 2023-04-18 13:25 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify para Windows
1.2.9.743.g85d9593d
Spicetify v2.16.2
```

### 📝 Description

When I run spicetify it works fine, I can play music and I don't have problems, but the marketplace and extensions downloaded from it dosn't work.

### 📸 Screenshots

![Desktop Screenshot 2023 04 18 - 15 22 26 07](https://user-images.githubusercontent.com/101269769/232790928-9ffc5a29-a8d0-4124-b8db-269a4704349f.png)

**Comment by kyrie25** [comment] 2023-04-18 13:41
Duplicate of #2270

**Closed by kyrie25** 2023-04-18 13:41 UTC
Labels: 🐛 bug, 🔵 extension
