### ISSUE TITLE
Error on executing "spicetify apply"

### ISSUE THREAD

**Issue by BunnyFunner** [spicetify/spicetify-cli#1672] opened 2022-05-14 13:37 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [ ] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
1.1.85.895.g2a71e1b8
- Spicetify version:
spicetify v2.9.8
```

### 📝 Description

I reinstall spicetify and the same error.

### 📸 Screenshots

![Captura de pantalla 2022-05-14 153727](https://user-images.githubusercontent.com/22412136/168428180-e420a7fd-6478-4500-91be-034413767471.png)

**Comment by ririxidev** [comment] 2022-05-14 13:55
Duplicate of #1660

**Closed by ririxidev** 2022-05-14 13:55 UTC
Labels: 🐛 bug
